GET https://chat-funny-api.vercel.app/

### Get users list

GET https://chat-funny-api.vercel.app/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDgwYWIxZWQwNjUzNzBjMzNmOTc1MGMiLCJpYXQiOjE2ODgyMzkwNjksImV4cCI6MTY4ODIzOTM2OX0.N8DJq6XifYrwuMdKwF1VRGSUGdpKd5ZTlspTuWLgA7U

### Register account

POST https://chat-funny-api.vercel.app/v1/users/register
Content-Type: application/json

{
    "username": "kiennt",
    "password": "kmnkmn123"
}
### Refresh token

POST https://chat-funny-api.vercel.app/v1/users/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDAyM2NiOTNhNzUyYWIwNDJkZWExODAiLCJpYXQiOjE2NzgxMjYwMzcsImV4cCI6MTcwOTY4MzYzN30.PH9JAi1q0ZtDcWF7hbXfi_uhTRDabhaA9Q0NkGbFNqk"
}

### Login

POST https://chat-funny-api.vercel.app/v1/users/login
Content-Type: application/json

{
    "username": "kiennt",
    "password": "kmnkmn123"
}

### Update

PATCH https://chat-funny-api.vercel.app/v1/users/6480ab1ed065370c33f9750c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDgwYWIxZWQwNjUzNzBjMzNmOTc1MGMiLCJpYXQiOjE2ODYxNTQzNzcsImV4cCI6MTY4NjE1NDY3N30.CSxNbDcw2iulCy_Pnk6nyWRBbmb769MRX7LP21Y4a9w
Content-Type: application/json

{
    "nickname": "Ngô Trung Kiên",
    "rooms": ["6480ab72d065370c33f97510"]
}

### Logout

POST https://chat-funny-api.vercel.app/v1/users/logout
Content-Type: application/json

{
    "refreshToken": "bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDdkNDU5MGEwZDZkYzdmYmM5MzhiZWIiLCJpYXQiOjE2ODU5NDY5NTcsImV4cCI6MTcxNzUwNDU1N30.3cCChxCu4ninJsD5sWZ-DibTJjLlhmp3kBVPGO4vK1o"
}


#------------------------- Room --------------------------#
### Create

POST https://chat-funny-api.vercel.app/v1/rooms
Content-Type: application/json

{
  "type": 0,
  "users": []
}

### Update
PATCH https://chat-funny-api.vercel.app/v1/rooms/6480ab72d065370c33f97510
Content-Type: application/json

{
  "avatar": "https://kiennt.ga",
  "name": "update group",
  "type": 1,
  "users": ["6480ab1ed065370c33f9750c"]
}

### Delete
DELETE https://chat-funny-api.vercel.app/v1/rooms/647d85c2ed5e7c2ed37673e8
Content-Type: application/json

### Get list
GET https://chat-funny-api.vercel.app/v1/rooms
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDdkODViNGVkNWU3YzJlZDM3NjczZTYiLCJpYXQiOjE2ODYwNjkwNzQsImV4cCI6MTY4NjA2OTM3NH0.M85Q8KrEIEPxyn7Vh_dxtI4iX2pvqScRNoZ_y1_UWKc

### Get list message in room
GET https://chat-funny-api.vercel.app/v1/rooms/6480ab72d065370c33f97510/messages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDgwYWIxZWQwNjUzNzBjMzNmOTc1MGMiLCJpYXQiOjE2ODgzMTI4MzQsImV4cCI6MTY4ODMxMzEzNH0.w5GqFWKelVeKlM27WsboMgN2E8-EACDCMCxvPDnh1y0

### Get detail
GET https://chat-funny-api.vercel.app/v1/rooms/6480ab72d065370c33f97510

#------------------------- Message --------------------------#
### Create

POST https://chat-funny-api.vercel.app/v1/messages
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDgwYWIxZWQwNjUzNzBjMzNmOTc1MGMiLCJpYXQiOjE2ODgzMjEyOTksImV4cCI6MTY4ODMyMTU5OX0.WDvIgj7MO2QoM_N-Q-DpP-lmarNu_Tr9651RVHwimKk

{
  "roomId": "6480ab72d065370c33f97510",
  "userSendId": "649dcd8fd88aae8cadde54d1",
  "userReveiceId": "6480ab1ed065370c33f9750c",
  "text": "Hello, World!",
  "files": [],
  "isSeen": ["649dcd8fd88aae8cadde54d1"]
}

### Update
PATCH https://chat-funny-api.vercel.app/v1/messages/6480d53027bd179f318dc483
Content-Type: application/json

{
  "files": ["648200e56bde84483c306781"],
  "text": "update text"
}

### Delete
DELETE https://chat-funny-api.vercel.app/v1/messages/6480b2fc3d2e7664ea8086f4
Content-Type: application/json

### Get list
GET https://chat-funny-api.vercel.app/v1/messages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDdkODViNGVkNWU3YzJlZDM3NjczZTYiLCJpYXQiOjE2ODYwNjkwNzQsImV4cCI6MTY4NjA2OTM3NH0.M85Q8KrEIEPxyn7Vh_dxtI4iX2pvqScRNoZ_y1_UWKc


### Get detail
GET https://chat-funny-api.vercel.app/v1/messages/6480b2fc3d2e7664ea8086f4

#------------------------- File --------------------------#
### Create

POST https://chat-funny-api.vercel.app/v1/files
Content-Type: application/json

{
  "name": "file",
  "url": "https://kiennt.ga",
  "messageId": "6480d53027bd179f318dc483"
}

### Update
PATCH https://chat-funny-api.vercel.app/v1/files/6481ffaf6bde84483c306773
Content-Type: application/json

{
  "url": "https://kiennt.ga",
  "messageId": "6480d53027bd179f318dc483"
}

### Delete
DELETE https://chat-funny-api.vercel.app/v1/files/6481ffaf6bde84483c306773
Content-Type: application/json

### Get list
GET https://chat-funny-api.vercel.app/v1/files
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDdkODViNGVkNWU3YzJlZDM3NjczZTYiLCJpYXQiOjE2ODYwNjkwNzQsImV4cCI6MTY4NjA2OTM3NH0.M85Q8KrEIEPxyn7Vh_dxtI4iX2pvqScRNoZ_y1_UWKc


### Get detail
GET https://chat-funny-api.vercel.app/v1/files/6481ffaf6bde84483c306773